default_search_engine: DuckDuckGo
news_sources:
- api_endpoint: https://news.google.com/rss/search?q={keyword}&hl=en-US&gl=US&ceid=US:en
  enabled: true
  name: Google News
  type: rss
- api_endpoint: https://newsapi.org/v2/everything
  enabled: false
  name: NewsAPI
  params:
    language: en
    pageSize: 10
    q: '{keyword}'
    sortBy: publishedAt
  type: api
- enabled: true
  name: DuckDuckGo
  params:
    max_results: 10
    region: us-en
    safesearch: moderate
    timelimit: w
  type: duckduckgo
